#!/usr/bin/env python3.10

name = input("What is your name? ")
birthdate = input("What is your birthdate? ")
age = int(input("How old are you? "))

print(f"{name} was born on {birthdate}.")
print(f"You will be 50 years old in {50 - age} years.")
